# Generated by Django 5.1.15 on 2026-07-08 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spent_on", models.DateField()),
                ("description", models.CharField(max_length=200)),
                ("original_amount_minor", models.BigIntegerField()),
                ("original_currency", models.CharField(max_length=3)),
                ("amount_base_minor", models.BigIntegerField()),
                (
                    "fx_rate",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                (
                    "fx_rate_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "split_type",
                    models.CharField(
                        choices=[
                            ("equal", "equal"),
                            ("unequal", "unequal"),
                            ("percentage", "percentage"),
                            ("share", "share"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("void", "void")],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("source_row_number", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="groups.expensegroup",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="expenses_paid",
                        to="groups.person",
                    ),
                ),
            ],
            options={
                "db_table": "expense",
            },
        ),
        migrations.CreateModel(
            name="ExpenseShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_input",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("computed_owed_minor", models.BigIntegerField()),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="expenses.expense",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shares",
                        to="groups.person",
                    ),
                ),
            ],
            options={
                "db_table": "expense_share",
            },
        ),
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("rate_to_base", models.DecimalField(decimal_places=6, max_digits=12)),
                ("effective_date", models.DateField()),
            ],
            options={
                "db_table": "fx_rate",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("currency", "effective_date"),
                        name="uq_fx_currency_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate_to_base__gt", 0)),
                        name="fx_rate_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency__in", ["INR", "USD"])),
                        name="fx_currency_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("settled_on", models.DateField()),
                ("note", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("manual", "manual"),
                            ("reclassified_from_import", "reclassified_from_import"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="settlements_sent",
                        to="groups.person",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="groups.expensegroup",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="settlements_received",
                        to="groups.person",
                    ),
                ),
            ],
            options={
                "db_table": "settlement",
            },
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["group", "spent_on"], name="ix_expense_group_date"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["paid_by"], name="ix_expense_payer"),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("original_amount_minor__gte", -1000000000),
                    ("original_amount_minor__lte", 10000000000),
                ),
                name="expense_amount_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_currency__in", ["INR", "USD"])),
                name="expense_currency_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("fx_rate__gt", 0)), name="expense_fx_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="expenseshare",
            index=models.Index(fields=["person"], name="ix_share_person"),
        ),
        migrations.AddConstraint(
            model_name="expenseshare",
            constraint=models.UniqueConstraint(
                fields=("expense", "person"), name="uq_share_expense_person"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseshare",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("share_input__isnull", True),
                    ("share_input__gte", 0),
                    _connector="OR",
                ),
                name="share_input_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(fields=["group"], name="ix_settlement_group"),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gt", 0)),
                name="settlement_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_person", models.F("to_person")), _negated=True
                ),
                name="settlement_no_self",
            ),
        ),
    ]
