"""Generate the Import Report deliverable by ingesting the real xlsx.

Runs the full detection pipeline inside a rolled-back transaction (nothing persists),
so it can be re-run any time to regenerate docs/import_report.md.

    python manage.py generate_import_report
"""
from collections import Counter
from datetime import date
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand
from django.db import transaction

from apps.accounts.models import User
from apps.expenses.models import FxRate
from apps.groups.models import ExpenseGroup, Membership, Person, PersonAlias
from apps.imports.services.import_service import ImportService

TODAY = date(2026, 7, 9)


class Command(BaseCommand):
    help = "Generate docs/import_report.md from the provided expenses xlsx."

    def handle(self, *args, **options):
        xlsx = Path(settings.BASE_DIR).parent / "EXPENSE FILE" / "expenses_export assigbment annex.xlsx"
        out = Path(settings.BASE_DIR).parent / "docs" / "import_report.md"
        out.parent.mkdir(exist_ok=True)

        with transaction.atomic():
            group = self._scaffold_group()
            svc = ImportService()
            batch = svc.ingest(group, xlsx.name, xlsx.read_bytes())
            svc.run_detectors(batch, TODAY)
            report = svc.report(batch)
            for a in batch.anomalies.filter(status="pending"):
                svc.resolve(a, "approved")
            result = svc.commit(batch, TODAY)
            out.write_text(self._render(report, result))
            transaction.set_rollback(True)  # leave the DB untouched

        self.stdout.write(self.style.SUCCESS(
            f"Wrote {out} — {len(report)} anomalies, "
            f"{len(set(r['anomaly_type'] for r in report))} types."))

    def _scaffold_group(self):
        user = User.objects.create_user(email="_report@splito.local", display_name="Report", password="x")
        g = ExpenseGroup.objects.create(name="_report", created_by=user)
        people = {n: Person.objects.create(group=g, canonical_name=n)
                  for n in ["Aisha", "Rohan", "Priya", "Meera", "Sam"]}
        Person.objects.create(group=g, canonical_name="Dev", is_guest=True)
        PersonAlias.objects.create(group=g, person=people["Priya"], raw_alias="Priya S")
        for n in ["Aisha", "Rohan", "Priya"]:
            Membership.objects.create(group=g, person=people[n], joined_on=date(2026, 2, 1))
        Membership.objects.create(group=g, person=people["Meera"],
                                  joined_on=date(2026, 2, 1), left_on=date(2026, 3, 31))
        Membership.objects.create(group=g, person=people["Sam"], joined_on=date(2026, 4, 8))
        FxRate.objects.get_or_create(currency="USD", effective_date=date(2026, 1, 1),
                                     defaults={"rate_to_base": "83.50"})
        return g

    def _render(self, report, result):
        by_type = Counter(r["anomaly_type"] for r in report)
        lines = [
            "# Import Report", "",
            "_Generated by `python manage.py generate_import_report` against "
            "`expenses_export assigbment annex.xlsx` (unedited)._", "",
            f"**{len(report)} anomalies** across **{len(by_type)} types**. "
            "Nothing is committed to the ledger until each blocking anomaly is approved.", "",
            "## Commit outcome (all anomalies approved)", "",
            f"- Expenses created: **{result['created']}**",
            f"- Settlements created: **{result['settlements']}**",
            f"- Duplicates voided: **{result['voided']}**",
            f"- Rows skipped (needed correction): **{len(result['skipped'])}**", "",
            "## Anomalies by type", "",
            "| type | count |", "|------|-------|",
        ]
        for t, c in by_type.most_common():
            lines.append(f"| `{t}` | {c} |")
        lines += ["", "## Every anomaly detected", "",
                  "| row | severity | type | detail | proposed action |",
                  "|-----|----------|------|--------|-----------------|"]
        for r in sorted(report, key=lambda x: (x["severity"], x["row_number"])):
            lines.append(f"| {r['row_number']} | {r['severity']} | `{r['anomaly_type']}` "
                         f"| {r['detail']} | `{r['proposed_action']}` |")
        if result["skipped"]:
            lines += ["", "## Skipped rows (held back, not silently dropped)", ""]
            for s in result["skipped"]:
                lines.append(f"- row {s['row']}: {s['reason']}")
        return "\n".join(lines) + "\n"
