# Generated by Django 5.1.15 on 2026-07-08 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("committed", "committed")],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="groups.expensegroup",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_batch",
            },
        ),
        migrations.CreateModel(
            name="StagedRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("raw_json", models.JSONField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="imports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "staged_row",
            },
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("exact_dup", "exact_dup"),
                            ("fuzzy_dup", "fuzzy_dup"),
                            ("pct_not_100", "pct_not_100"),
                            ("unequal_sum_mismatch", "unequal_sum_mismatch"),
                            ("ambiguous_date", "ambiguous_date"),
                            ("out_of_bounds_date", "out_of_bounds_date"),
                            ("missing_payer", "missing_payer"),
                            ("missing_currency", "missing_currency"),
                            ("negative_amount", "negative_amount"),
                            ("zero_amount", "zero_amount"),
                            ("sub_unit_amount", "sub_unit_amount"),
                            ("type_detail_conflict", "type_detail_conflict"),
                            ("non_member", "non_member"),
                            ("ex_member", "ex_member"),
                            ("settlement_as_expense", "settlement_as_expense"),
                            ("name_alias", "name_alias"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("block", "block"), ("warn", "warn")], max_length=8
                    ),
                ),
                ("detail", models.CharField(max_length=300)),
                (
                    "proposed_action",
                    models.CharField(
                        choices=[
                            ("void_dup", "void_dup"),
                            ("merge", "merge"),
                            ("reclassify_settlement", "reclassify_settlement"),
                            ("normalize_name", "normalize_name"),
                            ("convert_currency", "convert_currency"),
                            ("exclude_person", "exclude_person"),
                            ("request_input", "request_input"),
                            ("reject", "reject"),
                            ("skip", "skip"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("edited", "edited"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("resolved_value", models.JSONField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "staged_row",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="imports.stagedrow",
                    ),
                ),
            ],
            options={
                "db_table": "anomaly",
            },
        ),
        migrations.AddIndex(
            model_name="stagedrow",
            index=models.Index(fields=["batch"], name="ix_staged_batch"),
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(fields=["batch"], name="ix_anomaly_batch"),
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(fields=["status"], name="ix_anomaly_status"),
        ),
        migrations.AddConstraint(
            model_name="anomaly",
            constraint=models.CheckConstraint(
                condition=models.Q(("severity__in", ["block", "warn"])),
                name="anomaly_severity_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="anomaly",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "approved", "rejected", "edited"])
                ),
                name="anomaly_status_valid",
            ),
        ),
    ]
